[package]
name = "mqttparse"
version = "0.1.0"
authors = ["Rajasekharan Vengalil <avranju@gmail.com>"]

[features]
std = []

[dependencies]
byteorder = "1.2"
bitfield = "0.13.1"

[dev-dependencies]
rayon = "1.0"
