[package]
name = "embedded-mqtt"
version = "0.1.0"
authors = ["Keith Duncan <keith_duncan@me.com>"]
publish = false

[features]
std = ["byteorder/std"]

[dependencies]
byteorder = { version = "1.2", default-features = false }
bitfield = "0.13.1"

[dev-dependencies]
rayon = "1.0"
